---
title: "Lecture7"
output: html_document
date: "2023-09-26"
---

```{r setup}
library(tidyverse)
```
# Wide format to long format

```{r}
pulse_df = 
  haven::read_sas("./Data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |> #bdi is on different columns
  pivot_longer( #wide format to long format
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    #get rid of name
    names_prefix = "bdi_score_",
    values_to = "bdi_score"
  ) |> 
  mutate(
    #check the visit variable and replace every bl to 00m
    visit = replace(visit, visit == "bl","00m")
  )
pulse_df
```
```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv")|>
  janitor::clean_names() |> 
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight"
  ) |> 
  mutate(
    gd = case_match( #multiple things to change and change to numerical variable
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight"~ 18
    )
  )
litters_df
```
# Bind rows 
## Import LoTR data

```{r}
fellowship_df = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring") #specify the movie title 

two_towers_df = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king_df = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_df = bind_rows(fellowship_df, two_towers_df, return_king_df) |> 
  janitor::clean_names() |> 
  pivot_longer(
    male:female,
    names_to = "gender",
    values_to = "word"
  ) |> 
  relocate(movie)
lotr_df
```

# Join datasets
```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv")|>
  janitor::clean_names() |> 
  mutate(wt_gain = gd18_weight-gd0_weight) |> 
  select(litter_number, group, wt_gain) |> 
  #separate the group variable into 2 columns
  separate(group, into = c("dose","day_of_tx"),3) #seperate at 3rd character
litters_df

pup_df = 
  read_csv("./data/FAS_pups.csv") |>
  janitor::clean_names() |>
  mutate(
    sex=case_match(
      sex,
      1~"male",
      2~"female"
    )
  )
pup_df

fas_df=
  left_join(pup_df, litters_df, by = "litter_number") #merge on litter number
fas_df
```



