---
title: "Read_Data_Web"
author: "Jasmine Zhang"
date: "2023-10-12"
output: html_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)
```
## Extracting tables
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)
drug_use_html

drug_use_html |>
  html_table() #imports all 15 tables from the web
```

```{r the first table}
marj_use_df =
  drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1) #remove the first row
```

## CSS selectors
```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

swm_title_vec = swm_html |> 
  html_elements(".lister-item-header a") |> 
  html_text()

swm_gross_vec = swm_html |> 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |> 
  html_text()

```

```{r}
swm_df = tibble(
  title = swm_title_vec,
  gross_rev = swm_gross_vec
)
```

## APIs
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```
```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
```
```{r}
poke = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()

poke$name
```





