---
title: "Strings_factors"
author: "Jasmine Zhang"
date: "2023-10-17"
output: html_document
---

```{r setup}
library(rvest)
library(p8105.datasets)
library(tidyverse)
```

# Strings and regex

```{r}
string_vec = c("my", "name", "is", "jeff")
string_vec
str_detect(string_vec, "jeff")
str_detect(string_vec, "e") #doesnt have to match exactly, but does it appear at all
str_replace(string_vec, "jeff", "Jeff")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )
str_detect(string_vec, "^i think") #^: only start with "i think"
str_detect(string_vec, "i think$") #$: ends with "i think"
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )
str_detect(string_vec,"[Pp]umpkin") #[Pp]: match either P or p 
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )
str_detect(string_vec, "^[0-9][a-zA-Z]") #number first followed immediately by a letter (no space)

```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )
str_detect(string_vec, "7.11") #. captures any character in between 7 and 11
str_detect(string_vec, "7\\.11") #\\. captures an actual . in between but not special operator
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )
str_detect(string_vec, "\\[") #\\: capture the real [
```

# Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex #gives info on levels

as.numeric(vec_sex)
```

```{r}
#relevel
vec_sex = fct_relevel(vec_sex, "male") #relevel male to 1 and female to 2
as.numeric(vec_sex)
```

# NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |>
  slice(-1)
```

```{r Tidy dataset strings}
data_marj = table_marj |> 
  select(-contains("P Value")) |> #removes every columns with P Value
  pivot_longer(
    -State,
    names_to = "age_yr",
    values_to = "percent"
  ) |> 
  separate(age_yr, into = c("age", "year"), sep = "\\(") |> #separate on (
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)
  ) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
```

```{r Tidy dataset factors}
data_marj |>
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> #order state on axis based on percent value
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# Restaurant inspections data
```{r}
data("rest_inspec")
rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade, 
    values_from = n)

rest_inspec =
  rest_inspec |>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |> 
  mutate(boro = str_to_title(boro))
```
```{r}
rest_inspec |> 
  filter(str_detect(dba, "Pizza")) |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(names_from = grade, values_from = n)
#include all possibilities of pizza
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(names_from = grade, values_from = n)

```

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |>
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |>
  mutate(boro = fct_infreq(boro)) |> #number of pizza places
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |>
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Manhattan", "The City")) |> #rename a borough
  #makes boro back to strings, when plotted in alphebatical order
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
#when using factors
rest_inspec |> 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) |>
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro, "The City" = "Manhattan")) |>
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

# Weather dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
#relevel the name 
weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
#reorder based on tmax 
weather_df |>
  mutate(name = forcats::fct_reorder(name, tmax)) |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")

```
```{r linear model}
#linear regression: reference group change
weather_df |>
  lm(tmax ~ name, data = _)
weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  lm(tmax ~ name, data = _)
```


